// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ToDoListDBContext))]
    [Migration("20250322211402_decorator")]
    partial class decorator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Models.Taak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Taken");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2025, 3, 1, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dit is de beschrijving voor taak 1",
                            IsHighlighted = false,
                            Title = "Test Taak1",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2025, 3, 2, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dit is de beschrijving voor taak 2",
                            IsHighlighted = false,
                            Title = "Test Taak2",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2025, 3, 3, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dit is de beschrijving voor taak 3",
                            IsHighlighted = false,
                            Title = "Test Taak3",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2025, 3, 4, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Je kunt het al raden dit is ook een beschrijving, maar dan voor taak 4 :)",
                            IsHighlighted = false,
                            Title = "Test Taak4",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
